<footer class="p-footer">
    <div class="row">
        <div class="col-12">
            <p>Build on top of <a href="https://vanillaframework.io/" target="_blank">Vanilla</a></p>
            <nav class="p-footer__nav">
                <ul class="p-footer__links">
                    <li class="p-footer__item">
                        <a class="p-footer__link" href="#">Source code</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</footer>
